defaults:
  - _self_
  - serve: qwenvl_32_instruct
experiment:
  exp_name: qwenvl_32_instruct
  exp_dir: outputs/${experiment.exp_name}
  task:
    type: serve
  deploy:
    use_fs_serve: false
  runner:
    ssh_port: 22
  envs:
    CUDA_DEVICE_MAX_CONNECTIONS: 1
action: run
hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
