defaults:
  - _self_
  - serve: deepseek_v3

experiment:
  exp_name: deepseek_v3
  exp_dir: outputs/${experiment.exp_name}
  task:
    type: serve
    backend: vllm
    entrypoint: null
  runner:
    hostfile: examples/deepseek/conf/hostfile.txt
    ssh_port: 22 # replace with your ssh port
  envs:
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    USE_FLAGGEMMS: true
  cmds:
    before_start: source /root/miniconda3/bin/activate flagscale-inference && export GLOO_SOCKET_IFNAME=bond0 # replace "bond0" with your own network card
  

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
