defaults:
  - train: train_qwen2_5_vl_7b.yaml
  - _self_

experiment:
  exp_name: train_qwen2_5_vl_7b
  exp_dir: ./${experiment.exp_name}
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/train_qwen2_5_vl.py
  runner:
    backend: torchrun
    nnodes: 1
    nproc_per_node: 8
    hostfile: null
  envs:
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    UB_SKIPMC: 1

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
