defaults:
  - _self_
  - inference: inference_aquila_7b

experiment:
  exp_name: aquila2
  exp_dir: ./outputs
  task:
    type: inference
    backend: vllm
    entrypoint: ./flagscale/inference/inference_aquila.py
  runner:
    hostfile: null
  envs:
    CUDA_VISIBLE_DEVICES: 0
    CUDA_DEVICE_MAX_CONNECTIONS: 1

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra 
