defaults:
  - train: demo_hetero 
  - _self_

experiment:
  exp_name: aquila2
  exp_dir: ./outputs
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/train_gpt.py
  runner:
    hostfile: torchrun # Please replace with your actual hostfile path
    rdzv_backend: "static" # hetero training only supports static
  envs:
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    CUDA_DEVICE_MAX_CONNECTIONS: 1
  cmds:
    before_start: "ulimit -n 1048576"
    after_stop: ""

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra 
