defaults:
- _self_
- serve: serve_qwen2.5_7b

experiment:
  exp_name: qwen2.5_7b
  exp_dir: outputs/${experiment.exp_name}
  task:
    type: serve
  deploy:
    port: 10001
    use_fs_serve: false
    prefill_decode_disaggregation: true
    prefill_num: 1
    prefill_address: x.x.x.x # optional, default "auto"
    decode_num: 2
    decode_address: x.x.x.x # optional, default "auto"
  runner:
    hostfile: examples/qwen/conf/hostfile.txt
    docker: fr-v2
  envs:
    CUDA_DEVICE_MAX_CONNECTIONS: 1
  cmds:
    before_start: source /root/miniconda3/bin/activate flagscale-inference

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
